classdef Building
    % Propiedades de la clase
    properties
        % Posición predeterminada
        x = 0
        y = 0
        z = 0
        % Tamaño predeterminado
        sx = 10
        sy = 10
        sz = 10
    end
    
    methods
        % Constructor de la clase
        function obj = Building(size)
            if nargin > 0
                obj.sx = size(1);
                obj.sy = size(2);
                obj.sz = size(3);
            end
        end
        
        % Método para establecer la posición del edificio
        function obj = SetPos(obj, pos)
            obj.x = pos(1);
            obj.y = pos(2);
            obj.z = pos(3);
        end
        
        % Método para generar el SDF
        function sdf = GenerateSDF(obj)
            color = [0.9, 0.9, 0.9];
            alpha = 1;
            
            sdf = sprintf(['<model name="building_%d_%d">\n',...
                           '   <pose>%d %d %d</pose>\n',...
                           '   <static>true</static>\n',...
                           '   <link name="link">\n',...
                           '      <collision name="collision_building">\n',...
                           '         <geometry>\n',...
                           '            <box>\n',...
                           '               <size>%d %d %d</size>\n',...
                           '            </box>\n',...
                           '         </geometry> \n',...
                           '         <surface>\n',...
                           '            <friction>\n',...
                           '               <ode>\n',...
                           '                  <mu>100.0</mu>\n',...
                           '                  <mu2>50.0</mu2>\n',...
                           '                  <slip1>0.0</slip1>\n',...
                           '                  <slip2>0.0</slip2>\n',...
                           '               </ode>\n',...
                           '            </friction>\n',...
                           '         </surface>\n',...
                           '      </collision>\n',...
                           '      <visual name="visual_tierra">\n',...
                           '         <geometry>\n',...
                           '            <box>\n',...
                           '               <size>%d %d %d</size>\n',...
                           '            </box>\n',...
                           '         </geometry>\n',...
                           '         <material>\n',...
                           '            <ambient>%f %f %f %f</ambient>\n',...
                           '            <diffuse>%f %f %f %f</diffuse>\n',...
                           '            <specular>%f %f %f %f</specular>\n',...
                           '         </material>\n',...
                           '      </visual>\n',...
                           '      <self_collide>0</self_collide>\n',...
                           '      <kinematic>0</kinematic>\n',...
                           '      <gravity>1</gravity>\n',...
                           '   </link>\n',...
                           '</model>\n'],...
                           obj.x, obj.y,...
                           obj.x, obj.y, obj.z + (obj.sz/2),...
                           obj.sx, obj.sy, obj.sz,...
                           obj.sx, obj.sy, obj.sz,...
                           color(1), color(2), color(3), alpha,...
                           color(1), color(2), color(3), alpha,...
                           color(1), color(2), color(3), alpha);
        end
    end
end
