classdef World
    properties
        % Default position
        x = 0
        y = 0
        z = 0
        % Default size
        sx = 1000
        sy = 1000
        sz = 1
        % Streets size
        streets_size = [10, 20]
        % Buildings
        buildings = Building.empty(1000000, 0)
        buildings_total = 0;
        %Figure
        world_fig
    end
    
    methods
        function obj = World(init_pos, size)
            if nargin > 0
                obj.x = init_pos(1);
                obj.y = init_pos(2);
                obj.z = init_pos(3);
                obj.sx = size(1);
                obj.sy = size(2);
            end
        end
        
        % Method to add a building to the world
        function obj = addBuilding(obj, building)
            obj.buildings(obj.buildings_total + 1) = building;
            obj.buildings_total = obj.buildings_total + 1;
        end

        function createFig(obj)
            obj.world_fig = figure('Name', 'World', 'NumberTitle', 'off');
            figure(obj.world_fig);
            clf(obj.world_fig);

            for building = obj.buildings
                b_size = [building.sx building.sy building.sz];
                b_pos = [building.x building.y building.z];
                plotcube(b_size, b_pos - [b_size(1:2)/2 0], 0.1, [0.5, 0.5, 0.5]);
            end
            xlim([0-obj.sx/2 obj.sx/2]);
            xlabel("X");
            ylim([0-obj.sy/2 obj.sy/2]);
            ylabel("Y");
        end
        
        % Method to generate .sdf file
        function sdf = generateSDF(obj)
            color = [1, 0.7, 0];
            alpha = 1;
            
            building_sdf = '';
            for i = 1:length(obj.buildings)
                building = obj.buildings(i);
                building_sdf = strcat(building_sdf, building.GenerateSDF());
            end
            
            sdf = sprintf(['<?xml version="1.0"?><sdf version="1.7"><world name="default">' ...
                           '   <scene>\n',...
                           '      <ambient>0.5 0.5 0.5 1.0</ambient>\n',...
                           '      <shadows>true</shadows>\n',...
                           '   </scene>\n',...
                           '   <include>\n',...
                           '      <uri>model://sun</uri>\n',...
                           '   </include>\n',...
                           '   <!-- Camera -->\n',...
                           '   <gui fullscreen="0">\n',...
                           '      <camera name="user_camera">\n',...
                           '         <pose>0 0 1000 -1.57 1.57 0</pose>\n',...
                           '         <view_controller>orbit</view_controller>\n',...
                           '         <projection_type>perspective</projection_type>\n',...
                           '      </camera>\n',...
                           '   </gui>\n',...
                           '   <model name="tierra">\n',...
                           '      <pose>%d %d %d</pose>\n',...
                           '      <static>true</static>\n',...
                           '      <link name="link">\n',...
                           '         <collision name="collision_tierra">\n',...
                           '            <geometry>\n',...
                           '               <box>\n',...
                           '                  <size>%d %d %d</size>\n',...
                           '               </box>\n',...
                           '            </geometry> \n',...
                           '            <surface>\n',...
                           '               <friction>\n',...
                           '                  <ode>\n',...
                           '                     <mu>100.0</mu>\n',...
                           '                     <mu2>50.0</mu2>\n',...
                           '                     <slip1>0.0</slip1>\n',...
                           '                     <slip2>0.0</slip2>\n',...
                           '                  </ode>\n',...
                           '               </friction>\n',...
                           '            </surface>\n',...
                           '         </collision>\n',...
                           '         <visual name="visual_tierra">\n',...
                           '            <geometry>\n',...
                           '               <box>\n',...
                           '                  <size>%d %d %d</size>\n',...
                           '               </box>\n',...
                           '            </geometry>\n',...
                           '            <material>\n',...
                           '               <ambient>%f %f %f %f</ambient>\n',...
                           '               <diffuse>%f %f %f %f</diffuse>\n',...
                           '               <specular>%f %f %f %f</specular>\n',...
                           '            </material>\n',...
                           '         </visual>\n',...
                           '         <self_collide>0</self_collide>\n',...
                           '         <kinematic>0</kinematic>\n',...
                           '         <gravity>1</gravity>\n',...
                           '      </link>\n',...
                           '   </model>\n',...
                           '%s',...
                           '<plugin name="UTRAFMAN_gazebo" filename="libUTRAFMAN_gazebo.so" />', ...
                           '</world></sdf>'],...
                           obj.x, obj.y, obj.z - obj.sz,...
                           obj.sx, obj.sy, obj.sz,...
                           obj.sx, obj.sy, obj.sz,...
                           color(1), color(2), color(3), alpha,...
                           color(1), color(2), color(3), alpha,...
                           color(1), color(2), color(3), alpha,...
                           building_sdf);
        end
    end
end